import React from 'react'
import classes from './Background.module.css'

const Background = () => {
  return (
    <div className={classes.bg}>
        <div className={`${classes.blocks} ${classes.blocks1}`}>
            <div><p>1</p></div>
            <div><p>2</p></div>
            <div><p>3</p></div>
            <div><p>4</p></div>
            <div><p>5</p></div>
            <div><p>6</p></div>
            <div><p>7</p></div>
            <div><p>8</p></div>
            <div><p>9</p></div>
            <div><p>10</p></div>
            <div><p>11</p></div>
            <div><p>12</p></div>
            <div><p>13</p></div>
            <div><p>14</p></div>
            <div><p>15</p></div>
            <div><p>16</p></div>
            <div><p>17</p></div>
            <div><p>18</p></div>
            <div><p>19</p></div>
            <div><p>20</p></div>
            <div><p>21</p></div>
            <div><p>22</p></div>
            <div><p>23</p></div>
            <div><p>24</p></div>
            <div><p>25</p></div>
            <div><p>26</p></div>
            <div><p>27</p></div>
            <div><p>28</p></div>
            <div><p>29</p></div>
            <div><p>30</p></div>
            <div><p>31</p></div>
            <div><p>32</p></div>
            <div><p>33</p></div>
            <div><p>34</p></div>
            <div><p>35</p></div>
            <div><p>36</p></div>
            <div><p>37</p></div>
            <div><p>38</p></div>
            <div><p>39</p></div>
            <div><p>40</p></div>
            <div><p>41</p></div>
            <div><p>42</p></div>
            <div><p>43</p></div>
            <div><p>44</p></div>
            <div><p>45</p></div>
            <div><p>46</p></div>
            <div><p>47</p></div>
            <div><p>48</p></div>
            <div><p>49</p></div>
            <div><p>50</p></div>
            <div><p>51</p></div>
            <div><p>52</p></div>
            <div><p>53</p></div>
            <div><p>54</p></div>
            <div><p>55</p></div>
            <div><p>56</p></div>
            <div><p>57</p></div>
            <div><p>58</p></div>
            <div><p>59</p></div>
            <div><p>60</p></div>
        </div>
        <div className={`${classes.blocks} ${classes.blocks2}`}>
            <div><p>1</p></div>
            <div><p>2</p></div>
            <div><p>3</p></div>
            <div><p>4</p></div>
            <div><p>5</p></div>
            <div><p>6</p></div>
            <div><p>7</p></div>
            <div><p>8</p></div>
            <div><p>9</p></div>
            <div><p>10</p></div>
            <div><p>11</p></div>
            <div><p>12</p></div>
            <div><p>13</p></div>
            <div><p>14</p></div>
            <div><p>15</p></div>
            <div><p>16</p></div>
            <div><p>17</p></div>
            <div><p>18</p></div>
            <div><p>19</p></div>
            <div><p>20</p></div>
            <div><p>21</p></div>
            <div><p>22</p></div>
            <div><p>23</p></div>
            <div><p>24</p></div>
            <div><p>25</p></div>
            <div><p>26</p></div>
            <div><p>27</p></div>
            <div><p>28</p></div>
            <div><p>29</p></div>
            <div><p>30</p></div>
            <div><p>31</p></div>
            <div><p>32</p></div>
            <div><p>33</p></div>
            <div><p>34</p></div>
            <div><p>35</p></div>
            <div><p>36</p></div>
            <div><p>37</p></div>
            <div><p>38</p></div>
            <div><p>39</p></div>
            <div><p>40</p></div>
            <div><p>41</p></div>
            <div><p>42</p></div>
            <div><p>43</p></div>
            <div><p>44</p></div>
            <div><p>45</p></div>
            <div><p>46</p></div>
            <div><p>47</p></div>
            <div><p>48</p></div>
            <div><p>49</p></div>
            <div><p>50</p></div>
            <div><p>51</p></div>
            <div><p>52</p></div>
            <div><p>53</p></div>
            <div><p>54</p></div>
            <div><p>55</p></div>
            <div><p>56</p></div>
            <div><p>57</p></div>
            <div><p>58</p></div>
            <div><p>59</p></div>
            <div><p>60</p></div>
        </div>
        <div className={`${classes.blocks} ${classes.blocks3}`}>
            <div><p>1</p></div>
            <div><p>2</p></div>
            <div><p>3</p></div>
            <div><p>4</p></div>
            <div><p>5</p></div>
            <div><p>6</p></div>
            <div><p>7</p></div>
            <div><p>8</p></div>
            <div><p>9</p></div>
            <div><p>10</p></div>
            <div><p>11</p></div>
            <div><p>12</p></div>
            <div><p>13</p></div>
            <div><p>14</p></div>
            <div><p>15</p></div>
            <div><p>16</p></div>
            <div><p>17</p></div>
            <div><p>18</p></div>
            <div><p>19</p></div>
            <div><p>20</p></div>
            <div><p>21</p></div>
            <div><p>22</p></div>
            <div><p>23</p></div>
            <div><p>24</p></div>
            <div><p>25</p></div>
            <div><p>26</p></div>
            <div><p>27</p></div>
            <div><p>28</p></div>
            <div><p>29</p></div>
            <div><p>30</p></div>
            <div><p>31</p></div>
            <div><p>32</p></div>
            <div><p>33</p></div>
            <div><p>34</p></div>
            <div><p>35</p></div>
            <div><p>36</p></div>
            <div><p>37</p></div>
            <div><p>38</p></div>
            <div><p>39</p></div>
            <div><p>40</p></div>
            <div><p>41</p></div>
            <div><p>42</p></div>
            <div><p>43</p></div>
            <div><p>44</p></div>
            <div><p>45</p></div>
            <div><p>46</p></div>
            <div><p>47</p></div>
            <div><p>48</p></div>
            <div><p>49</p></div>
            <div><p>50</p></div>
            <div><p>51</p></div>
            <div><p>52</p></div>
            <div><p>53</p></div>
            <div><p>54</p></div>
            <div><p>55</p></div>
            <div><p>56</p></div>
            <div><p>57</p></div>
            <div><p>58</p></div>
            <div><p>59</p></div>
            <div><p>60</p></div>
        </div>
        <div className={`${classes.blocks} ${classes.blocks4}`}>
            <div><p>1</p></div>
            <div><p>2</p></div>
            <div><p>3</p></div>
            <div><p>4</p></div>
            <div><p>5</p></div>
            <div><p>6</p></div>
            <div><p>7</p></div>
            <div><p>8</p></div>
            <div><p>9</p></div>
            <div><p>10</p></div>
            <div><p>11</p></div>
            <div><p>12</p></div>
            <div><p>13</p></div>
            <div><p>14</p></div>
            <div><p>15</p></div>
            <div><p>16</p></div>
            <div><p>17</p></div>
            <div><p>18</p></div>
            <div><p>19</p></div>
            <div><p>20</p></div>
            <div><p>21</p></div>
            <div><p>22</p></div>
            <div><p>23</p></div>
            <div><p>24</p></div>
            <div><p>25</p></div>
            <div><p>26</p></div>
            <div><p>27</p></div>
            <div><p>28</p></div>
            <div><p>29</p></div>
            <div><p>30</p></div>
            <div><p>31</p></div>
            <div><p>32</p></div>
            <div><p>33</p></div>
            <div><p>34</p></div>
            <div><p>35</p></div>
            <div><p>36</p></div>
            <div><p>37</p></div>
            <div><p>38</p></div>
            <div><p>39</p></div>
            <div><p>40</p></div>
            <div><p>41</p></div>
            <div><p>42</p></div>
            <div><p>43</p></div>
            <div><p>44</p></div>
            <div><p>45</p></div>
            <div><p>46</p></div>
            <div><p>47</p></div>
            <div><p>48</p></div>
            <div><p>49</p></div>
            <div><p>50</p></div>
            <div><p>51</p></div>
            <div><p>52</p></div>
            <div><p>53</p></div>
            <div><p>54</p></div>
            <div><p>55</p></div>
            <div><p>56</p></div>
            <div><p>57</p></div>
            <div><p>58</p></div>
            <div><p>59</p></div>
            <div><p>60</p></div>
        </div>
        <div className={`${classes.blocks} ${classes.blocks5}`}>
            <div><p>1</p></div>
            <div><p>2</p></div>
            <div><p>3</p></div>
            <div><p>4</p></div>
            <div><p>5</p></div>
            <div><p>6</p></div>
            <div><p>7</p></div>
            <div><p>8</p></div>
            <div><p>9</p></div>
            <div><p>10</p></div>
            <div><p>11</p></div>
            <div><p>12</p></div>
            <div><p>13</p></div>
            <div><p>14</p></div>
            <div><p>15</p></div>
            <div><p>16</p></div>
            <div><p>17</p></div>
            <div><p>18</p></div>
            <div><p>19</p></div>
            <div><p>20</p></div>
            <div><p>21</p></div>
            <div><p>22</p></div>
            <div><p>23</p></div>
            <div><p>24</p></div>
            <div><p>25</p></div>
            <div><p>26</p></div>
            <div><p>27</p></div>
            <div><p>28</p></div>
            <div><p>29</p></div>
            <div><p>30</p></div>
            <div><p>31</p></div>
            <div><p>32</p></div>
            <div><p>33</p></div>
            <div><p>34</p></div>
            <div><p>35</p></div>
            <div><p>36</p></div>
            <div><p>37</p></div>
            <div><p>38</p></div>
            <div><p>39</p></div>
            <div><p>40</p></div>
            <div><p>41</p></div>
            <div><p>42</p></div>
            <div><p>43</p></div>
            <div><p>44</p></div>
            <div><p>45</p></div>
            <div><p>46</p></div>
            <div><p>47</p></div>
            <div><p>48</p></div>
            <div><p>49</p></div>
            <div><p>50</p></div>
            <div><p>51</p></div>
            <div><p>52</p></div>
            <div><p>53</p></div>
            <div><p>54</p></div>
            <div><p>55</p></div>
            <div><p>56</p></div>
            <div><p>57</p></div>
            <div><p>58</p></div>
            <div><p>59</p></div>
            <div><p>60</p></div>
        </div>
    </div>
  )
}

export default Background